# https://docs.travis-ci.com/user/languages/android
language: android
android:
    components:
        # https://github.com/travis-ci/travis-ci/issues/5036
        - tools
        - platform-tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository

# Necessary because otherwise Gradle will OOM during the compilation phase:
# https://travis-ci.org/firebase/firebase-jobdispatcher-android/builds/164194294
# But also can't be >= 3gb, otherwise Travis will kill our process:
# https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error
env:
    - GRADLE_OPTS="-XX:MaxPermSize=1024m"

script:
    - ./gradlew jobdispatcher:build testapp:assemble

# "avoid uploading the cache after every build"
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
